### PR TITLE
Altered serial output in order to allow for serial plotter

### PR DESCRIPTION
**Pull request by John-Val**

### CODE REVIEW

**Comment by hideakitai** [comment]
Someone needs text output and someone needs plotter output. It is not the responsibility for the library (it depends on the user to select what to show), I'm thinking that it's better to remove printing functions from this library.

**Comment by John-Val** [comment]
Hi Hideaki,

Removing the printing options altogether is maybe a step to far. For beginners some initial output is nice to have, but of course this code can be put in the examples.

Again, thanks for the effort you put in your library.

John


Op 30 dec. 2020 3:59 p.m. schreef Hideaki Tai <notifications@github.com>:

Someone needs text output and someone needs plotter output. It is not the responsibility for the library (it depends on the user to select what to show), I'm thinking that it's better to remove printing functions from this library.

**Comment by hideakitai** [comment]
> Removing the printing options altogether is maybe a step to far. For beginners some initial output is nice to have, but of course this code can be put in the examples.

Yes, how to see the sensor output can be shown in examples. Also removing them can reduce program size caused by string literals. So I'm going to remove them.

**Comment by hideakitai** [comment]
I've removed printing functions at 00ad1a755c376ce63cfde210ea2ea56246515723 . Close this PR.

**Pull request closed without merging**
