### PR TITLE
More filters

### PR DESCRIPTION
**Pull request by John-Val**

### CODE REVIEW

**Comment by hideakitai** [comment]
I think adding more filters is acceptable, but I want to know:
- Why do you need additional filters?
- Why do you use `#ifdef`? I prefer to switch them dynamically

**Comment by John-Val** [comment]
Dear Hidea,

The Mahony filter can be used if your device is in a magnetic noisy environment. The none filter just for seeing the difference filtering makes.
I prefer the #if for it reduces the size of the compiled program, in my opinion important for the possibility of adding more functionality to an application on the device. I also think it might be preferable if the printing options are dealt with in the same fashion. If you do not use code, why load it on the microprocessor?

Best wishes,
John

Op 31 dec. 2020 1:28 a.m. schreef Hideaki Tai <notifications@github.com>:

I think adding more filters is acceptable, but I want to know:

  *   Why do you need additional filters?
  *   Why do you use #ifdef? I prefer to switch them dynamically

**Comment by hideakitai** [comment]
> The Mahony filter can be used if your device is in a magnetic noisy environment. The none filter just for seeing the difference filtering makes.

Ok, I think there's no problem.

> I prefer the #if for it reduces the size of the compiled program, 
>  If you do not use code, why load it on the microprocessor?

I think it should be changeable depending on the environment, not compile time. As you mentioned above, if there is magnetic noisy environment in the remote environment, how can you solve it?

> I also think it might be preferable if the printing options are dealt with in the same fashion.

I think it's too much. As I mentioned in #26,  each user has their own preference for how to display outputs. Maybe there will be many many preprocessor if everyone sends me PRs... So I think the printing format shouldn't be fixed by library.

**Comment by hideakitai** [comment]
@John-Val Can you make changes to adapt to latest master (v0.4.0)? It should be dynamically changeable. Also please rebase your commits in cleaner way. Or I will just copy and paste your filter codes by myself.

**Comment by John-Val** [comment]
Dear Hideaki,

Please go ahead copying the code whlie the next two weeks I have to spend all my time to teaching.
Kind  regards,
John
________________________________
Van: Hideaki Tai <notifications@github.com>
Verzonden: dinsdag 5 januari 2021 1:37
Aan: hideakitai/MPU9250 <MPU9250@noreply.github.com>
CC: John Val <j.val@rijnlandslyceum-rlo.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [hideakitai/MPU9250] More filters (#27)


@John-Val<https://github.com/John-Val> Can you make changes to adapt to latest master (v0.4.0)? It should be dynamically changeable. Also please rebase your commits in cleaner way. Or I will just copy and paste your filter codes by myself.

**Comment by hideakitai** [comment]
Done!

**Comment by John-Val** [comment]
Thank you

Op 6 jan. 2021 1:44 a.m. schreef Hideaki Tai <notifications@github.com>:

Done!

**Pull request closed without merging**
