### PR TITLE
Modified quaternion to rotation matrix calculations

### PR DESCRIPTION
**Pull request by HeyLlama**
:)

### CODE REVIEW

**Comment by hideakitai** [comment]
Why you made these changes? The default was air-plane coordinate, but why you changed it to raw coordinate?

**Comment by HeyLlama** [comment]
> Why you made these changes? The default was air-plane coordinate, but why you changed it to raw coordinate?

Oh! I needed the linear acceleration for a motion sensing project. It wasn't giving me proper gravity compensation until I made these changes. I also looked at someone else's RPY conversion and theirs matched the math equations. https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles -> Quaternion to Euler angles conversion; https://github.com/Josef4Sci/AHRS_Filter/blob/master/quaternion_library/quatern2euler.m

Sorry I'm wrong...I don't know much about airplane coordinate 😅

**Comment by hideakitai** [comment]
I've added missing linear acceleration to latest master branch. Please check it again.

The calculation of raw device coordinate is not correct now, so I'll fix it later in the appropriate way. If your problem is just linear acceleration, there's no need to modify the calculation now. I can't merge this PR as is, because this PR includes multiple context (not JUST for linear acceleration).

**Comment by HeyLlama** [comment]
Gotcha! Thank you for making this library! Saved me a lot of time :D

**Comment by hideakitai** [comment]
I'm happy supporting your project :). I'll refactor them to be able to get correct raw coordinates before releasing v0.4.0, please check if it works correctly again.

**Pull request closed without merging**
